# Generated by Django 2.1.7 on 2019-11-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='类名', max_length=50, verbose_name='分类名称')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击率')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=999, verbose_name='库存数')),
                ('market_price', models.FloatField(default=0, verbose_name='市场价')),
                ('shop_price', models.FloatField(default=0, verbose_name='销售价')),
                ('goods_desc', models.TextField(default='', verbose_name='商品详情')),
                ('goods_rank', models.IntegerField(default=5, verbose_name='商品登记')),
                ('goods_thumbnail', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热卖')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类别名称')),
                ('desc', models.TextField(default='', help_text='分类描述', verbose_name='分类描述')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
    ]
