# Generated by Django 2.1.7 on 2019-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191107_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_rank',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='商品等级'),
        ),
    ]
